import { Skill, Employee } from './types';

export const SKILLS: Skill[] = [
  { key: 'iown', label: 'IOWN APN' },
  { key: 'pm', label: 'プロジェクトマネジメント' },
  { key: 'frontend', label: 'フロントエンド開発' },
  { key: 'backend', label: 'バックエンド開発' },
  { key: 'ai', label: 'AI/機械学習' },
  { key: 'network', label: 'ネットワーク技術' },
  { key: 'security', label: 'セキュリティ' },
];

export const EMPLOYEES: Employee[] = [
  {
    id: '1',
    name: '山田 太郎',
    department: '技術開発部',
    role: 'シニアエンジニア',
    description: 'IOWN APNの開発リーダー。PMとしての経験も豊富。',
    skills: {
      iown: 95,
      pm: 85,
      frontend: 60,
      backend: 80,
      ai: 45,
      network: 90,
      security: 70,
    },
  },
  {
    id: '2',
    name: '佐藤 花子',
    department: 'プロダクト開発部',
    role: 'プロジェクトマネージャー',
    description: 'PMとして多数のプロジェクトを成功に導いた実績あり。',
    skills: {
      iown: 40,
      pm: 95,
      frontend: 50,
      backend: 45,
      ai: 35,
      network: 55,
      security: 60,
    },
  },
  {
    id: '3',
    name: '鈴木 一郎',
    department: 'AI研究所',
    role: 'リサーチエンジニア',
    description: 'AI/機械学習の専門家。バックエンドにも精通。',
    skills: {
      iown: 30,
      pm: 50,
      frontend: 40,
      backend: 85,
      ai: 95,
      network: 45,
      security: 65,
    },
  },
  {
    id: '4',
    name: '田中 美咲',
    department: 'フロントエンド開発部',
    role: 'リードエンジニア',
    description: 'UI/UXに強いフロントエンドエンジニア。',
    skills: {
      iown: 25,
      pm: 60,
      frontend: 95,
      backend: 50,
      ai: 40,
      network: 35,
      security: 55,
    },
  },
  {
    id: '5',
    name: '高橋 健太',
    department: 'セキュリティ部門',
    role: 'セキュリティスペシャリスト',
    description: 'セキュリティとネットワークの専門家。',
    skills: {
      iown: 50,
      pm: 55,
      frontend: 35,
      backend: 70,
      ai: 30,
      network: 85,
      security: 95,
    },
  },
  {
    id: '6',
    name: '伊藤 由美',
    department: 'バックエンド開発部',
    role: 'シニアエンジニア',
    description: 'バックエンドとネットワークに精通したエンジニア。',
    skills: {
      iown: 60,
      pm: 65,
      frontend: 45,
      backend: 90,
      ai: 50,
      network: 80,
      security: 75,
    },
  },
  {
    id: '7',
    name: '渡辺 隆',
    department: 'プロダクト開発部',
    role: 'フルスタックエンジニア',
    description: 'フロントエンドとバックエンドの両方をカバー。',
    skills: {
      iown: 35,
      pm: 70,
      frontend: 80,
      backend: 85,
      ai: 55,
      network: 60,
      security: 65,
    },
  },
  {
    id: '8',
    name: '中村 直美',
    department: 'IOWN開発部',
    role: 'テクニカルリード',
    description: 'IOWN APNとネットワーク技術のエキスパート。',
    skills: {
      iown: 90,
      pm: 75,
      frontend: 55,
      backend: 75,
      ai: 40,
      network: 95,
      security: 80,
    },
  },
];
